export enum $V {
    CORE_POPUP,
    CORE_DESTROY_POPUP,
    CORE_DESTROY_ALL_POPUP,
    CORE_SCROLL,

    SELECTED_CELL,
    CLEAR_MOVED,

    LOCATIONS,
    EVENTS,

    // Direction Hover
    GRID_START_MOVE,
    GRID_DIRECTION_HORIZONTAL,
    GRID_DIRECTION_TOP,
    GRID_DIRECTION_BOTTOM,
    GRID_DIRECTION_RIGHT,
    GRID_DIRECTION_LEFT,

    GRID_DIRECTION_FINAL,

    PUSH_EVENT,


}